# Example application config (copy to app.yaml and edit)
source: "0"
model: models/yolov8n.pt
confidence: 0.3
device: cpu
save_output: false
output_path: outputs/output.mp4
no_view: false
imgsz: 640
max_frames: null
line_bottom: false
line_bottom_offset: 0
line_vertical_center: false
line_vertical_offset: 0
edit_line: false
save_line_path: config/line.yaml
half: false
mode: body
line_band_px: 0
show_trails: true
rtsp_prefer_quality: false
roi_show: true
video_speed_mult: 1.0
